spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:contrato
    username: sa
    password:
    path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
springdoc:
#   show-actuator: true
#   pathsToMatch: /api/**/v1/**
   swagger-ui:
    use-root-path: true
